### ISSUE TITLE
创建任务时允许输入期望完成时间或期望完成时长

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-plugins-service-management#131]
**描述您的需求**  
创建任务时允许输入期望完成时间或期望完成时长，以便于更好地展示待处理的任务列表。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by royl88** [comment]
v0.6.0 中已支持超时，并以不同颜色区分超时时间。
