### ISSUE TITLE
支持将表单数据通过接口发送给其他系统

### ISSUE THREAD

**Issue by nertonsong** [WeBankPartners/wecube-plugins-service-management#51]
**描述您的需求**  
支持将表单数据通过接口发送给其他系统，
1.参数示例：
{"handler":"lisi","formType":"BDAP_CREATE_DB","data":"W3siZGJfbmFtZSI6ImltZF9kYXRhYmFua19vZHNfbWFzayIsInN1cHBvcnRfYW5hbHlzaXNfcmF0\naW8iOiIxMDAiLCJvcGVyX3R5cGUiOiIxIiwidXNlcl9uYW1lIjoiaGR1c2VyMTA5OCIsInN1cHBv\ncnRfb25saW5lX3JhdGlvIjoiMCJ9XQ==","createTime":" 2019-11-27 16:53:35","envType":"1","createUser":"zhangsan","requestNo":10021039,"recordSource":"newsystem"}

2.参数备注:
handler：单子处理人
formType：自定义的表单ID
data：被加密的表单内容
createTime：ITSM单创建时间
envType：环境1表示测试，2表示生产
createUser：表单的申请人
requestNo：ITSM单号
recordSource：表单的来源

3.返回样例：
#接受成功
	{
	"code": 0,
	"data":null,
	"message":"success"
	}
#接受失败
	{
	"code": 500,
	"data":null,
	"message":<error message>
	}

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by haixinhuang** [comment]
经讨论后，用 #73 已实现，待联调，关闭此issue
