### ISSUE TITLE
service management页面展示的时间和本地时间不一致

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-service-management#68]
**描述您遇到的bug**  
wecube页面展示的时间和本地时间不一致。
![image](https://user-images.githubusercontent.com/17095701/71226323-7b1d6c80-2316-11ea-8d92-31c6867b693f.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by haixinhuang** [comment]
与 #67 重复
